### ISSUE TITLE
Move static constants on path following from `FlxObject` to `FlxPath`

### ISSUE THREAD

**Issue by IQAndreas** [FlixelCommunity/flixel#112]
Right now, the static constants are located in `FlxObjects`, so defining them looks like this:

``` as3
sprite.followPath(new FlxPath(path), 30, FlxObject.PATH_FORWARD);
```

I feel all those static constants should be moved to FlxPath, so you get this:

``` as3
sprite.followPath(new FlxPath(path), 30, FlxPath.FORWARD);
```

**Comment by Dovyski** [comment]
Landed in https://github.com/FlixelCommunity/flixel/commit/cfdd9d838ed89bc825fa52fa183e73c045c32c8e.
