### ISSUE TITLE
Fix for issue 63 causes problems with looping sounds

### ISSUE THREAD

**Issue by wgr** [FlixelCommunity/flixel#120]
I ran into flixel issue #160 ( https://github.com/AdamAtomic/flixel/issues/160 ) and decided to give your updated FlxSound.as ( https://github.com/FlixelCommunity/flixel/issues/63 ) a go. While it fixed that problem, unfortunately it caused a new one.

The problem: play a looping sound, then pause it, then resume it. When the looping sound reaches the end of it's loop, it will now start playing again from the point you paused it at (instead of from the beginning as would be expected).

I suspect the problem is related to line 451
_channel = _sound.play(_position, (_looped ? 9999 : 0), _transform);

From the Adobe docs:
play    ()  method
Parameters
startTime:Number (default = 0) — The initial position in milliseconds at which playback should start.
loops:int (default = 0) — Defines the number of times a sound loops back to the startTime value before the sound channel stops playback.
sndTransform:flash.media:SoundTransform (default = null) — The initial SoundTransform object assigned to the sound channel.

The relevant bit is "Defines the number of times a sound loops back to the startTime value".
I think after the looping sound completes it's 1st loop, the startTime needs to be set back to 0.

I believe this may have been the purpose of the looped() method in the original FlxSound (which I noticed was removed) which calls play() which sets the position back to 0.

**Comment by Dovyski** [comment]
Thanks for the report, @wgr , we will analyze it.

@IQAndreas I will update the FlixelSandbox project so we can test it easily.

**Comment by IQAndreas** [comment]
I have confirmed this. Thanks for pointing it out.

That's a rather odd default behavior of AS3's sound class, but the fix is easy. I'll go ahead and include the change in the currently open pull request for FlxSound to avoid merge issues.

**Comment by wgr** [comment]
Thanks, I tried your fix in my project and it appears to work well.

**Comment by IQAndreas** [comment]
Resolved in 7e5f1e0504151e8e9b306a444c5eaa6e10817472
