### ISSUE TITLE
FlxPath ignoreDrawDebug doesn't work

### ISSUE THREAD

**Issue by WingEraser** [FlixelCommunity/flixel#122]
I’ve use the `PathFindingDemo` to produce this bug. First I’ve remove `PlayState::draw()` to use the `DebugPathDisplay` on the “correct way”. 

In the `PlayState::create()` I added this:

``` as3
_unit.path = new FlxPath();
_unit.path.ignoreDrawDebug = true;
```

It should automatically added to the `DebugPathDisplay` when you create a new `FlxPath`.

The debug path line still shows. The reason is a new `FlxPath` is created to show the line which doesn’t `ignoreDrawDebug` of course. It’s inside the `FlxTilemap::findPath()`.

**Comment by moly** [comment]
I don't think this is a bug, it's how I would expect flixel to work. If you don't want the path to show up while debugging, set `ignoreDrawDebug` when you create it:

``` as3
private function moveToGoal():void
{
    if (_action == ACTION_IDLE)
    {       
        //Find path to goal from unit to goal
        var path:FlxPath = _map.findPath(new FlxPoint(_unit.x + _unit.width / 2, _unit.y + _unit.height / 2), new FlxPoint(_goal.x + _goal.width / 2, _goal.y + _goal.height / 2));

        //Don't draw when debugging
        path.ignoreDrawDebug = true;

        //Tell unit to follow path
        _unit.followPath(path);
        _action = ACTION_GO;
    }
}
```

**Comment by Dovyski** [comment]
I agree with you, @moly . This is an old issue and there was no reply within 2 months. I think it's safe to close it.

**Comment by WingEraser** [comment]
I see. I'll close it.
