### ISSUE TITLE
Adding FlxParticles to FlxEmitter results in odd behaviour

### ISSUE THREAD

**Issue by wgr** [FlixelCommunity/flixel#123]
I came across what I'm pretty certain is a bug in flixel while trying to help someone today. However I have been unable to track down the exact cause, and I haven't seen it reported anywhere else. I am reporting it here in case you guys are interested in fixing it.

Since FlxEmitter extends FlxGroup, it should be possible to add FlxParticles to it. Flash game dojo confirms this should work in theory: http://flashgamedojo.com/wiki/index.php?title=Emitter_Creation_(Flixel)

**After copy-pasting the FGDojo code I get really strange results:**
**\- The particles emitted from the emitter have the flixel default f-logo**
**\- The actual particle graphic appears motionless at 0,0**

_(Note: I think instead of adding FlxSprites to the emitter, the FGDojo code should add FlxParticles - but using either sprite or particle makes no difference to the results.)_

By using the makeParticles function on the emitter, it behaves correctly. So why does it work with makeParticles but not by manually adding? I looked at the makeParticles source and I can see absolutely nothing special about it... it simply creates FlxParticles just like the FGDojo code.

A user on the forums posted this workaround... it appears that by using makeParticles first, it is then possible to modify the created particles to customize them. But this is a kinda clunky way of doing it http://forums.flixel.org/index.php/topic,6900.msg38395.html#msg38395

Anyways, it would be great to get this working because sometimes you want access to additional features when creating your particles that are not included in the makeparticles function.

**Comment by moly** [comment]
You need to set the particle's `exist` to false before you add them, otherwise the emitter wont recycle them. This works for me:

``` as3
var emitter:FlxEmitter = new FlxEmitter(100,100); //x and y of the emitter
var particles:int = 5;

for(var i:int = 0; i < particles; i++)
{
    var particle:FlxParticle = new FlxParticle();
    particle.makeGraphic(2, 2, 0xffffffff);
    particle.exists = false;
    emitter.add(particle);
}

add(emitter);
emitter.start();
```

**Comment by wgr** [comment]
Thanks, I could swear I tried that but I must have done something wrong cause it works now.

So I guess it's just the Flash Game Dojo documentation that needs updating.

1 more thing in case anybody else ever comes across this: you also need to set emitter.maxSize = particles, otherwise if the default size is less than the number of particles you are adding it won't be able to recycle them and you'll see the flixel logo for some particles again.
