### ISSUE TITLE
Add a 'bounce' function to FlxSprite

### ISSUE THREAD

**Issue by Gama11** [FlixelCommunity/flixel#125]
Effects like bouncing / knockback are needed to make a game more juicy. I've modified my FlxSprite.as by adding these two nifty little functions that offsets a sprite into a given x or y-direction for a very short amount of time:

``` actionscript
public function bounce(X:int = 0, Y:int = -5):void
{
    if (knockbackTimer.isRunning) return;

    knockbackTimer.start(3 / 60, 1, endKnockback);

    bounceOffset.x = X;
    bounceOffset.y = Y;
    y += bounceOffset.y;
    x += bounceOffset.x;
}

private function endKnockback(t:FlxTimer):void
{
    knockbackTimer.stop();

    x -= bounceOffset.x;
    y -= bounceOffset.y;
}
```

The knockbackTimer also needs to be instantiated, which I did in the constructor.

``` actionscript
knockbackTimer = new FlxTimer();
```

**Comment by SeiferTim** [comment]
I don't know that you would want this inside the core FlxSprite class...

**Comment by Gama11** [comment]
So... Are you implying it's a bad idea in general, or just something that should be added elsewhere? 

It just seemed like the most convenient place to me, as you can just call sprite.bounce() that way. I guess you could also have a bounce-function in FlxG that works with any FlxSprite / FlxGroup given to it via parameter, as there are other effects like FlxG.shake, FlxG.fade or FlxG.flash, but then again, those effects affect the whole screen, not just one sprite.

**Comment by SeiferTim** [comment]
I don't think it's a bad idea, just that FlxSprites are used for a ton of other things that probably wouldn't need any kind of 'bouncing' added to them... I could see another class that extends FlxSprite that might want to have that included, or even better maybe a seperate class for special effects that you could add any FlxObject to... not sure how it could be implemented like that, but I don't think it should be a part of FlxSprite directly...

**Comment by IQAndreas** [comment]
> Even better maybe a separate class for special effects that you could add any FlxObject to... not sure how it could be implemented like that, but I don't think it should be a part of FlxSprite directly...

I agree, this functionality would be great in plugin format, but doesn't belong right in the `FlxSprite`.

Since the code doesn't require any private properties on the `FlxSprite`, it should be able to adjust to become a plugin quite well. 

If you want some "inspiration" on how to create a plugin for Flixel, I believe that [FlixelPowerTools](https://github.com/photonstorm/Flixel-Power-Tools) uses `FlxPlugin` for its classes, but it's been a while since I used them, so you may need to double check. Otherwise the class is rather simple and straight forward, so a quick look at its methods should let you know which functions to override in your plugin.

**Comment by Dovyski** [comment]
I agree with @SeiferTim  and @IQAndreas. A plugin is the perfect match for that. It can be a plugin with several other effects, not just bounce.

**Comment by Gama11** [comment]
Well, yeah, plugin sounds good, but there'd need to be (plenty of) other effects to make it wortwhile. Can't really think of similar effects right now.

**Comment by Dovyski** [comment]
Take a look at this (huge) list: http://daneden.me/animate. Lots of nice effects. It would be great to have some of them in a plugin.

**Comment by Gama11** [comment]
Oh, cool list. Most of them can be achieved easily with Tweening libraries like TweenLite though, which I use in conjunction with Flixel. Actually, I recently had a look at haxeflixel, and they actually have tweening there. I think it'd be awesome to port that to AS3 and integrate it! 

Edit: I just created an [issue for adding Tweening to flixel](https://github.com/FlixelCommunity/flixel/issues/129). That probably even covers this bouncing effect, which I guess could be achieved with that, too, so this issue seems obsolete.
