### ISSUE TITLE
FlxTilemap() can't draw one-column tilemap - BitmaData exception

### ISSUE THREAD

**Issue by antongrechko** [FlixelCommunity/flixel#212]
When I try to call `loadMap(FlxTilemap.arrayToCSV(constructBoundsArray("LEFT"), 1) ...` flash throws

```
ArgumentError: Error #2015: Invalid BitmapData.
    at flash.display::BitmapData/ctor()
    at flash.display::BitmapData()
    at org.flixel.system::FlxTilemapBuffer()[E:\workspace-flash\frameworks\AdamAtomic-flixel-8989e50\org\flixel\system\FlxTilemapBuffer.as:72]
    at org.flixel::FlxTilemap/draw()[E:\workspace-flash\frameworks\AdamAtomic-flixel-8989e50\org\flixel\FlxTilemap.as:426]
```

It making impossible to draw a "one-column" tilemap (border for something, as example)
Fix is:  in `FlxTilemap.loadMap()` function find rows

```
                columns = rows[row++].split(",");
                if(columns.length <= 1)
```

replace `<=` with `<`
That should work.

**Comment by Dovyski** [comment]
Thanks for the report and the fix. We should work on this issue soon.

**Comment by Gama11** [comment]
Thanks, now fixed in HaxeFlixel. :thumbsup:

**Comment by WingEraser** [comment]
Many thanks from flixel-gdx :+1:

**Comment by Dovyski** [comment]
It took us a while, but it's fixed in Flixel Community too :D 
Landed in https://github.com/FlixelCommunity/flixel/commit/3f66f8da48acafbe431235e00e6a4633acee6544.
