### ISSUE TITLE
Bump version 2.58 to 3.0

### ISSUE THREAD

**Issue by Dovyski** [FlixelCommunity/flixel#221]
When we released `v2.56`, it was ok to keep `2` as the major version number, since the API was identical to the previous one. A handful of bugfixes were made, but things remained retro-compatible.

That's not the case with `v2.58` anymore. As our [feature planning table](https://github.com/FlixelCommunity/flixel/issues/193) shows, several changes have been made to the API: classes were moved, method signatures were changed, new (complex) features were added, etc.

I think we should bump Flixel Community version to `3.0`. This simple change will make it clear to any developer that things have changed significantly. Sticking with `2.5x` will cause confusion and frustration for developers.

**Comment by IQAndreas** [comment]
> This simple change will make it clear to any developer that things have changed significantly.

Excellent idea! I agree wholeheartedly.

**Comment by Dovyski** [comment]
Great! I will edit all milestones and our planning table.
